apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: aws-secret-store
spec:
  provider:
    aws:
      service: SecretsManager
      region: ap-south-1
      # Authentication options:
      # - Recommended (production): use IRSA / IAM role via service account (see README)
      # - Alternative: reference a Kubernetes Secret containing AWS credentials (shown below)
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: aws-credentials
            key: access-key-id
          secretAccessKeySecretRef:
            name: aws-credentials
            key: secret-access-key
