apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: aws-secret-store
spec:
  provider:
    aws:
      service: SecretsManager
      region: ap-south-1
      # Authentication: no explicit auth configured so the operator will use the
      # EC2 instance metadata credentials (instance profile). Ensure the EC2
      # nodes running the ExternalSecrets operator have an instance profile
      # with permission to read the `hrms/mysql` secret in Secrets Manager.
