apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets-resources
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  destination:
    server: https://kubernetes.default.svc
  project: hrms
  source:
    repoURL: https://github.com/PookieLand/gitops-manifests
    path: base/external-secrets
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
