# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: kafka2-topics-init-production
#   namespace: argocd
#   annotations:
#     argocd.argoproj.io/sync-wave: "2"
# spec:
#   project: default
#   source:
#     repoURL: 'https://github.com/PookieLand/gitops-manifests.git'
#     targetRevision: main
#     path: base/kafka2-topics-init/overlays/production
#   destination:
#     server: https://kubernetes.default.svc
#     namespace: production
#   syncPolicy:
#     automated:
#       prune: true
#       selfHeal: true
#     syncOptions:
#       - CreateNamespace=true
#       - ServerSideApply=true
