apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets-operator
  namespace: argocd
spec:
  destination:
    namespace: external-secrets
    server: https://kubernetes.default.svc
  project: hrms
  source:
    repoURL: https://charts.external-secrets.io
    chart: external-secrets
    targetRevision: "1.0.0"
    helm:
      values: |
        installCRDs: true
        replicaCount: 1
        fullnameOverride: "external-secrets"
        # Configure ServiceAccount and annotations to support IRSA or other auth methods.
        # If you're using EKS IRSA, set the annotation `eks.amazonaws.com/role-arn` on the serviceAccount below.
        serviceAccount:
          create: true
          # Uncomment and set the annotation for IRSA (replace with your role ARN):
          # annotations:
          #  eks.amazonaws.com/role-arn: arn:aws:iam::<ACCOUNT_ID>:role/<ROLE_NAME>
          # name: external-secrets
        controller:
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
