apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets-resources
  namespace: argocd
spec:
  destination:
    namespace: hrms
    server: https://kubernetes.default.svc
  project: hrms
  source:
    repoURL: https://github.com/PookieLand/gitops-manifests
    path: base/mysql
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
