apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka-staging
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://charts.bitnami.com/bitnami'
    chart: kafka
    targetRevision: 28.1.0
    helm:
      valueFiles:
        - ../../base/services/kafka-service/values-staging.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: kafka-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
