apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hrms-compliance-service
  namespace: {{ .Values.namespace }}
spec:
  project: hrms
  source:
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    path: "{{ .Values.spec.source.path }}/compliance-service"
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: hrms
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
