apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: logging-fluent-bit
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/PookieLand/grafana-component'
    path: gitops-manifests/base/logging/fluent-bit
    targetRevision: main
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: logging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
