apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: hrms-mysql-credentials
  namespace: hrms
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: mysql-credentials
    creationPolicy: Owner
  data:
    - secretKey: MYSQL_ROOT_PASSWORD
      remoteRef:
        key: hrms/mysql
        property: MYSQL_ROOT_PASSWORD
    - secretKey: MYSQL_USER
      remoteRef:
        key: hrms/mysql
        property: MYSQL_USER
    - secretKey: MYSQL_PASSWORD
      remoteRef:
        key: hrms/mysql
        property: MYSQL_PASSWORD
