apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: aws-secrets-manager
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
      # Authentication: no explicit `secretRef` is provided so the AWS SDK will use the
      # ambient credentials available to the process. In your current setup (non-EKS),
      # that means the operator running in a pod will pick up the EC2 instance profile
      # credentials from the node's instance metadata (IMDS).
      #
      # This matches the Terraform in `HRMS/terraform/secrets.tf` which creates an
      # IAM role + instance profile (`externalsecret_profile`) and is intended to be
      # attached to the EC2 instances running the Kubernetes nodes. Ensure the
      # instance profile is attached to the instances so the operator can assume it.
      #
      # If you later move to EKS, you can switch to IRSA by creating an IAM role
      # with a web identity trust and annotating the operator service account
      # (see `argo/templates/app-external-secrets-operator.yaml`).
