apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mysql-staging
  namespace: staging
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: aws-secrets
    kind: ClusterSecretStore
  target:
    name: mysql-staging
    creationPolicy: Owner
  data:
    - secretKey: MYSQL_PASSWORD
      remoteRef:
        key: hrms/mysql
        property: MYSQL_PASSWORD
    - secretKey: MYSQL_ROOT_PASSWORD
      remoteRef:
        key: hrms/mysql
        property: MYSQL_ROOT_PASSWORD
    - secretKey: MYSQL_USER
      remoteRef:
        key: hrms/mysql
        property: MYSQL_USER
