apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: opensearch-credentials
  namespace: staging
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secret-store
    kind: ClusterSecretStore
  target:
    name: opensearch-credentials
  data:
    - secretKey: username
      remoteRef:
        key: opensearch
        property: username
    - secretKey: password
      remoteRef:
        key: opensearch
        property: password
    - secretKey: host
      remoteRef:
        key: opensearch
        property: host
