apiVersion: kafka.strimzi.io/v1
kind: KafkaNodePool
metadata:
  name: dual-role
  labels:
    strimzi.io/cluster: kafka
spec:
  storage:
    type: persistent-claim
    size: 10Gi
    deleteClaim: false
