apiVersion: batch/v1
kind: Job
metadata:
  name: kafka-init
  namespace: default
spec:
  backoffLimit: 3
  ttlSecondsAfterFinished: 3600
  template:
    metadata:
      labels:
        app: kafka-init
    spec:
      serviceAccountName: kafka-init
      restartPolicy: Never
      containers:
      - name: kafka-init
        image: confluentinc/cp-kafka:7.6.0
        command:
          - /bin/sh
          - -c
          - |
            echo 'Waiting for Kafka to be ready...'
            sleep 10

            echo 'Creating Kafka topics for HRMS...'

            # User lifecycle events
            kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic user-created --partitions 3 --replication-factor 1
            kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic user-updated --partitions 3 --replication-factor 1
            kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic user-deleted --partitions 3 --replication-factor 1
            kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic user-suspended --partitions 3 --replication-factor 1
            kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic user-activated --partitions 3 --replication-factor 1
            kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic user-role-changed --partitions 3 --replication-factor 1

            # Onboarding events
            kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic user-onboarding-initiated --partitions 3 --replication-factor 1
            kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic user-onboarding-asgardeo-created --partitions 3 --replication-factor 1
            kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic user-onboarding-employee-created --partitions 3 --replication-factor 1
            kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic user-onboarding-completed --partitions 3 --replication-factor 1
            kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic user-onboarding-failed --partitions 3 --replication-factor 1

            # Special events (birthdays, anniversaries)
            kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic employee-special-birthday --partitions 3 --replication-factor 1
            kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic employee-special-work-anniversary --partitions 3 --replication-factor 1

            # HR events
            kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic hr-probation-ending --partitions 3 --replication-factor 1
            kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic hr-probation-ended --partitions 3 --replication-factor 1
            kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic hr-contract-expiring --partitions 3 --replication-factor 1
            kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic hr-contract-expired --partitions 3 --replication-factor 1
            kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic hr-performance-review-due --partitions 3 --replication-factor 1
            kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic hr-salary-increment-due --partitions 3 --replication-factor 1
            kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic hr-leave-balance-low --partitions 3 --replication-factor 1
            kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic hr-excessive-leave --partitions 3 --replication-factor 1

            # Notification events
            kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic notification-welcome-email --partitions 3 --replication-factor 1
            kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic notification-invitation-email --partitions 3 --replication-factor 1
            kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic notification-password-set --partitions 3 --replication-factor 1
            kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic notification-sent --partitions 3 --replication-factor 1
            kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic notification-failed --partitions 3 --replication-factor 1
            kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic notification-delivered --partitions 3 --replication-factor 1
            kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic notification-late-arrival --partitions 3 --replication-factor 1
            kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic notification-absent-employee --partitions 3 --replication-factor 1
            kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic notification-overtime-alert --partitions 3 --replication-factor 1
            kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic notification-leave-pending --partitions 3 --replication-factor 1
            kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic notification-leave-approved --partitions 3 --replication-factor 1
            kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic notification-leave-rejected --partitions 3 --replication-factor 1
            kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic notification-leave-reminder --partitions 3 --replication-factor 1

            # Audit events
            kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic audit-user-action --partitions 3 --replication-factor 1
            kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic audit-employee-action --partitions 3 --replication-factor 1
            kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic audit-attendance-action --partitions 3 --replication-factor 1
            kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic audit-leave-action --partitions 3 --replication-factor 1
            kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic audit-notification-action --partitions 3 --replication-factor 1
            kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic audit-compliance-action --partitions 3 --replication-factor 1

            # Employee events
            kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic employee-created --partitions 3 --replication-factor 1
            kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic employee-updated --partitions 3 --replication-factor 1
            kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic employee-deleted --partitions 3 --replication-factor 1
            kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic employee-terminated --partitions 3 --replication-factor 1
            kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic employee-promoted --partitions 3 --replication-factor 1
            kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic employee-transferred --partitions 3 --replication-factor 1
            kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic employee-salary-updated --partitions 3 --replication-factor 1
            kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic employee-salary-increment --partitions 3 --replication-factor 1
            kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic employee-contract-started --partitions 3 --replication-factor 1
            kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic employee-contract-renewed --partitions 3 --replication-factor 1
            kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic employee-contract-ended --partitions 3 --replication-factor 1
            kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic employee-probation-started --partitions 3 --replication-factor 1
            kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic employee-probation-completed --partitions 3 --replication-factor 1

            # Attendance events
            kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic attendance-checkin --partitions 3 --replication-factor 1
            kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic attendance-checkout --partitions 3 --replication-factor 1
            kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic attendance-updated --partitions 3 --replication-factor 1
            kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic attendance-late --partitions 3 --replication-factor 1
            kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic attendance-absent --partitions 3 --replication-factor 1
            kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic attendance-overtime --partitions 3 --replication-factor 1

            # Leave events
            kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic leave-requested --partitions 3 --replication-factor 1
            kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic leave-approved --partitions 3 --replication-factor 1
            kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic leave-rejected --partitions 3 --replication-factor 1
            kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic leave-cancelled --partitions 3 --replication-factor 1
            kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic leave-started --partitions 3 --replication-factor 1
            kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic leave-ended --partitions 3 --replication-factor 1

            # Compliance events
            kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic compliance-data-inventory-updated --partitions 3 --replication-factor 1
            kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic compliance-data-category-created --partitions 3 --replication-factor 1
            kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic compliance-data-category-updated --partitions 3 --replication-factor 1
            kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic compliance-retention-check --partitions 3 --replication-factor 1
            kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic compliance-retention-warning --partitions 3 --replication-factor 1
            kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic compliance-data-expired --partitions 3 --replication-factor 1
            kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic compliance-data-deleted --partitions 3 --replication-factor 1
            kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic compliance-data-access-request --partitions 3 --replication-factor 1
            kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic compliance-data-deletion-request --partitions 3 --replication-factor 1
            kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic compliance-data-export-request --partitions 3 --replication-factor 1
            kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic compliance-access-granted --partitions 3 --replication-factor 1
            kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic compliance-access-revoked --partitions 3 --replication-factor 1

            echo 'Listing all created topics:'
            kafka-topics --bootstrap-server kafka:29092 --list

            echo 'Kafka topics created successfully!'
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kafka-init
  namespace: default
