# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: test-service
#   namespace: production
#   labels:
#     app: test-service
# spec:
#   replicas: 2
#   selector:
#     matchLabels:
#       app: test-service
#   template:
#     metadata:
#       labels:
#         app: test-service
#     spec:
#       containers:
#       - name: test-service
#         image: nginx:1.25-alpine
#         ports:
#         - containerPort: 80
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: test-service
#   namespace: production
# spec:
#   selector:
#     app: test-service
#   ports:
#     - protocol: TCP
#       port: 80
#       targetPort: 80
#   type: ClusterIP
